name: Free VPS Auto Start with Telegram + Backup + Minecraft Auto Start

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours

jobs:
  start-vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Start tmate SSH
      id: tmate
      uses: mxschmitt/action-tmate@v3

    - name: Wait for tmate to initialize
      run: |
        echo "Waiting for tmate session..."
        sleep 15

    - name: Extract SSH command and save
      run: |
        SSH_COMMAND=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs \
          | grep -oE 'ssh [^"]*tmate.io' | head -n 1)
        echo "SSH_COMMAND=$SSH_COMMAND" >> $GITHUB_ENV
        echo "$SSH_COMMAND" > ssh.txt

    - name: Send SSH command to Telegram
      run: |
        curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="🔐 Your VPS SSH link:\n\n$SSH_COMMAND"

    - name: Commit SSH command to repo
      run: |
        git config --global user.email "bot@example.com"
        git config --global user.name "Auto VPS Bot"
        git pull
        git add ssh.txt
        git commit -m "Update SSH command"
        git push || echo "Nothing to push"

    - name: Prepare backup folder
      run: |
        mkdir -p ~/vps-backup/minecraft
        if [ -d ~/minecraft ]; then
          cp -r ~/minecraft/* ~/vps-backup/minecraft/ || true
        fi

    - name: Commit Minecraft backup to repo
      run: |
        cd ~/vps-backup || exit
        git init
        git config user.email "bot@example.com"
        git config user.name "Auto VPS Bot"
        git remote add origin https://github.com/${{ github.repository }}.git || true
        git pull origin main || true
        git add minecraft/
        git commit -m "Auto backup Minecraft server at $(date -u)" || true
        git push origin main --force

    - name: Auto start Minecraft server
      run: |
        chmod +x ~/vps-backup/minecraft/start-mc.sh || true
        ~/vps-backup/minecraft/start-mc.sh || echo "Minecraft server start script not found"
