name: Minecraft VPS Auto Start with Dropbox Backup & Discord Notify

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours

jobs:
  vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y openjdk-17-jre-headless wget unzip tmate zip curl

    - name: Create tmate session for SSH
      run: |
        tmate -S /tmp/tmate.sock new-session -d
        tmate -S /tmp/tmate.sock wait tmate-ready
        tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}' > ssh.txt
        cat ssh.txt

    - name: Send SSH info to Discord
      run: |
        ssh_url=$(cat ssh.txt)
        curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"🟢 Your VPS is ready! SSH: $ssh_url\"}" \
          "$DISCORD_WEBHOOK_URL"

    - name: Download Paper Minecraft server 1.20.1
      run: |
        mkdir -p minecraft
        cd minecraft
        wget -O paper.jar https://api.papermc.io/v2/projects/paper/versions/1.20.1/builds/196/downloads/paper-1.20.1-196.jar

    - name: Accept EULA
      run: echo "eula=true" > minecraft/eula.txt

    - name: Start Minecraft server (first run to generate files)
      run: |
        cd minecraft
        java -Xmx2G -Xms1G -jar paper.jar nogui || true

    - name: Download EssentialsX and Geyser plugins
      run: |
        mkdir -p minecraft/plugins
        wget -O minecraft/plugins/EssentialsX.jar https://github.com/EssentialsX/Essentials/releases/latest/download/EssentialsX.jar
        wget -O minecraft/plugins/Geyser.jar https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/standalone

    - name: Configure server.properties
      run: |
        echo "enable-command-block=true" >> minecraft/server.properties
        echo "motd=A Free GitHub Minecraft Server" >> minecraft/server.properties

    - name: Start Minecraft server in background
      run: |
        cd minecraft
        java -Xmx2G -Xms1G -jar paper.jar nogui &

    - name: Zip Minecraft world folder for backup
      run: |
        if [ -d minecraft/world ]; then
          zip -r world_backup.zip minecraft/world
        else
          echo "World folder not found, skipping zip."
        fi

    - name: Upload backup to Dropbox
      uses: zixia/upload-to-dropbox@v1
      with:
        token: ${{ secrets.DROPBOX_TOKEN }}
        source: world_backup.zip
        destination: /MinecraftBackups/world_backup_$(date +'%Y-%m-%d_%H-%M-%S').zip

    - name: Notify Discord backup done
      run: |
        curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"✅ Minecraft world backup uploaded to Dropbox!\"}" \
          "$DISCORD_WEBHOOK_URL"

    - name: Keep server alive for 6 hours
      run: sleep 21600
