name: Free VPS with Minecraft 1.20.1 Auto Start & Discord Notify

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours

jobs:
  minecraft-vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Java (OpenJDK 17)
      run: |
        sudo apt update
        sudo apt install -y openjdk-17-jre-headless

    - name: Make start.sh executable
      run: chmod +x start.sh

    - name: Run Minecraft server in background
      run: |
        nohup ./start.sh > server.log 2>&1 &

    - name: Setup tmate SSH session
      uses: mxschmitt/action-tmate@v3
      id: tmate

    - name: Wait for tmate
      run: sleep 15

    - name: Extract SSH command and save to ssh.txt
      run: |
        SSH_COMMAND=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs \
          | grep -oE 'ssh [^"]*tmate.io' | head -n 1)
        echo "$SSH_COMMAND" > ssh.txt
        echo "SSH_COMMAND=$SSH_COMMAND" >> $GITHUB_ENV

    - name: Commit ssh.txt to repo
      run: |
        git config --global user.name "Auto VPS Bot"
        git config --global user.email "bot@example.com"
        git pull
        git add ssh.txt
        git commit -m "Update SSH command"
        git push || echo "Nothing to commit"

    - name: Send SSH link to Discord
      run: |
        ssh_msg=$(cat ssh.txt)
        curl -H "Content-Type: application/json" \
             -X POST \
             -d "{\"content\": \"🟢 **Minecraft VPS Ready!**\n\n\`\`\`\n$ssh_msg\n\`\`\`\"}" \
             ${{ secrets.DISCORD_WEBHOOK }}
