name: Minecraft VPS Full Auto Setup with Dropbox & Discord

on: workflow_dispatch: schedule: - cron: "0 */6 * * *"  # Every 6 hours

jobs: start-minecraft-vps: runs-on: ubuntu-latest

steps:
- name: Checkout repository
  uses: actions/checkout@v3

- name: Install dependencies
  run: |
    sudo apt update
    sudo apt install -y tmate unzip default-jdk

- name: Start tmate SSH tunnel
  run: |
    tmate -F > tmate.log &
    sleep 10
    grep 'ssh' tmate.log > ssh.txt

- name: Send SSH to Discord
  run: |
    LINK=$(cat ssh.txt)
    curl -X POST -H "Content-Type: application/json" \
      -d "{\"content\": \"🟢 VPS Online!\n\n🔗 SSH: \\\\`${LINK}\\\`\"}" \
      "${{ secrets.DISCORD_WEBHOOK }}"

- name: Download and Setup Minecraft Server (PaperMC)
  run: |
    mkdir -p server/plugins
    cd server
    curl -o paper.jar https://api.papermc.io/v2/projects/paper/versions/1.20.1/builds/196/downloads/paper-1.20.1-196.jar
    echo "eula=true" > eula.txt
    echo "java -Xmx2048M -Xms1024M -jar paper.jar nogui" > start.sh
    chmod +x start.sh

- name: Download EssentialsX Plugin
  run: |
    cd server/plugins
    curl -LO https://github.com/EssentialsX/Essentials/releases/latest/download/EssentialsX.jar

- name: Download Geyser Plugin
  run: |
    cd server/plugins
    curl -LO https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
    mv spigot Geyser-Spigot.jar

- name: Start Minecraft Server Once to Generate Files
  run: |
    cd server
    bash start.sh &
    sleep 60
    pkill java

- name: Install Dropbox Uploader
  run: |
    git clone https://github.com/andreafabrizi/Dropbox-Uploader.git
    mv Dropbox-Uploader/dropbox_uploader.sh .
    chmod +x dropbox_uploader.sh
    echo "OAUTH_ACCESS_TOKEN=${{ secrets.DROPBOX_TOKEN }}" > ~/.dropbox_uploader

- name: Zip Server for Backup
  run: |
    zip -r server_backup.zip server

- name: Upload Backup to Dropbox
  run: |
    ./dropbox_uploader.sh upload server_backup.zip /Minecraft_Backups/server_backup_$(date +%Y-%m-%d_%H-%M).zip

- name: Done Notification to Discord
  run: |
    curl -X POST -H "Content-Type: application/json" \
      -d "{\"content\": \"✅ Server setup complete and backup uploaded!\"}" \
      "${{ secrets.DISCORD_WEBHOOK }}"

